### ISSUE TITLE
Values and Labels swapped on R6 and C2 (OTS_2)

### ISSUE THREAD

**Issue by wyojustin** [wyolum/VeloKey#11]
Value or label swapped on OTS_2 board: C2/R6 1uF/10K.

**Comment by Anool** [comment]
Labels are correct - C2 / R6
Values were swapped and are now corrected.

![screenshot from 2016-04-22 16 41 41](https://cloud.githubusercontent.com/assets/760425/14740093/e9e0510e-08a9-11e6-8c99-8610d82cb437.png)

**Comment by wyojustin** [comment]
Tested this configuration on unit #1.  Checks out.
