### ISSUE TITLE
VeloKey_V1 locks up

### ISSUE THREAD

**Issue by wyojustin** [wyolum/VeloKey#4]
VeloKey_V1 locks up.  Seems to software as vk_display test can run for hours without locking up.

**Comment by osbock** [comment]
have you performed a static analysis of RAM usage? or perhaps periodically
printing free_ram() periodically?

**Comment by Anool** [comment]
On the hardware side, try adding a large (10uF  ~ 47uF) cap across the M0 power supply pins to take care of the occasional supply brownout, or a 100nF cap to take care of noise.

**Comment by wyojustin** [comment]
Hard to test when it is intermittent.  Right now it seems to be working fine.

**Comment by wyojustin** [comment]
Figured it out.  When there is no bluetooth link it locks up.  Need to check bt before writing to EZKey

**Comment by wyojustin** [comment]
Looks like we need to monitor L2 on the EZLink for a 1/4 Hz sq wave.  This is the signal that a link is made.

https://learn.adafruit.com/introducing-bluefruit-ez-key-diy-bluetooth-hid-keyboard/pinouts

**Comment by wyojustin** [comment]
Successful testing connecting EZ-Key L2 --> A4.  Please update schematic @Anool

**Comment by Anool** [comment]
Connected EZKey L2 to M0 Pin A4

**Comment by Anool** [comment]
Connected EZKey L2 to M0 Pin A4

**Comment by wyojustin** [comment]
Fixed in SW.  Lock up occurs when trying to use BlueFruit when there is no link.   We now wait for link before starting BF serial.
