### ISSUE TITLE
Move line from display lite to A5

### ISSUE THREAD

**Issue by wyojustin** [wyolum/VeloKey#5]
We might want to save battery when inactive.  If we move display LITE to A5, we can toggle the back light  on and off as necessary.

**Comment by Anool** [comment]
A5 is the pin used for Power Up/Sleep. You mean to connect LCD LITE signal
to this same pin?
When M0 goes to sleep, so does the LCD, I thought.

Best Regards,

Anool Mahidharia
Work http://www.lumetron.com/
DiY http://www.wyolum.com/
Hackaday http://hackaday.com/about/
HackerSpace http://www.makersasylum.com
Git https://github.com/anool
Cycling http://cyclists.in/profile/AnoolJM
Workouts http://www.dailymile.com/people/anool
Flickr http://www.flickr.com/photos/anool
Picasa http://picasaweb.google.com/anool.m

**Comment by wyojustin** [comment]
https://learn.adafruit.com/assets/30320

I don't see any special functionality on the Feather A5 pin from this
printout.  I really don't care which pin though.

On Wed, Feb 17, 2016 at 12:32 AM, Anool Mahidharia <notifications@github.com

> wrote:
> 
> A5 is the pin used for Power Up/Sleep. You mean to connect LCD LITE signal
> to this same pin?
> When M0 goes to sleep, so does the LCD, I thought.
> 
> Best Regards,
> 
> Anool Mahidharia
> Work http://www.lumetron.com/
> DiY http://www.wyolum.com/
> Hackaday http://hackaday.com/about/
> HackerSpace http://www.makersasylum.com
> Git https://github.com/anool
> Cycling http://cyclists.in/profile/AnoolJM
> Workouts http://www.dailymile.com/people/anool
> Flickr http://www.flickr.com/photos/anool
> Picasa http://picasaweb.google.com/anool.m
> 
> On Wed, Feb 17, 2016 at 5:44 AM, Justin Shaw notifications@github.com
> wrote:
> 
> > Assigned #5 https://github.com/wyolum/VeloKey/issues/5 to @Anool
> > https://github.com/Anool.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/wyolum/VeloKey/issues/5#event-552847998.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wyolum/VeloKey/issues/5#issuecomment-185034515.

## 

Justin
justin@wyolum.com

**Comment by Anool** [comment]
LCD Display LITE pin connected to Pin 20 of M0

**Comment by wyojustin** [comment]
M0 pin does not have enough current to support display LITE.  Tested and failed.  Move display LITE pin back to 3v3.

**Comment by wyojustin** [comment]
Comment from Anool: 

> adding a simple transistor/FET will solve the display

**Comment by Anool** [comment]
Let's first try with adding a series resistor on the A3 "LITE" pin. About
100 to 220 ohms. If that doesn't work, a MOSFET/Transistor will.

Best Regards,

Anool Mahidharia
Work http://www.lumetron.com/
DiY http://www.wyolum.com/
Hackaday http://hackaday.com/about/
HackerSpace http://www.makersasylum.com
Git https://github.com/anool
Cycling http://cyclists.in/profile/AnoolJM
Workouts http://www.dailymile.com/people/anool
Flickr http://www.flickr.com/photos/anool
Picasa http://picasaweb.google.com/anool.m

**Comment by Anool** [comment]
How did you wire it up?
Per the data on Adafruit product page at :
https://www.adafruit.com/products/358
it says "2 white LED backlight, transistor connected so you can PWM dim the
backlight"

Which means you can connect micro controller pin directly to the LITE pin.

Best Regards,

Anool Mahidharia
Work http://www.lumetron.com/
DiY http://www.wyolum.com/
Hackaday http://hackaday.com/about/
HackerSpace http://www.makersasylum.com
Git https://github.com/anool
Cycling http://cyclists.in/profile/AnoolJM
Workouts http://www.dailymile.com/people/anool
Flickr http://www.flickr.com/photos/anool
Picasa http://picasaweb.google.com/anool.m

**Comment by wyojustin** [comment]
Tried on an analog pin and a digital pin full power.  Will try again soon.

J

On Mon, Mar 7, 2016 at 8:50 AM, Anool Mahidharia notifications@github.com
wrote:

> How did you wire it up?
> Per the data on Adafruit product page at :
> https://www.adafruit.com/products/358
> it says "2 white LED backlight, transistor connected so you can PWM dim the
> backlight"
> 
> Which means you can connect micro controller pin directly to the LITE pin.
> 
> Best Regards,
> 
> Anool Mahidharia
> Work http://www.lumetron.com/
> DiY http://www.wyolum.com/
> Hackaday http://hackaday.com/about/
> HackerSpace http://www.makersasylum.com
> Git https://github.com/anool
> Cycling http://cyclists.in/profile/AnoolJM
> Workouts http://www.dailymile.com/people/anool
> Flickr http://www.flickr.com/photos/anool
> Picasa http://picasaweb.google.com/anool.m
> 
> On Mon, Mar 7, 2016 at 2:05 PM, Anool Mahidharia anool.m@gmail.com
> wrote:
> 
> > Let's first try with adding a series resistor on the A3 "LITE" pin. About
> > 100 to 220 ohms. If that doesn't work, a MOSFET/Transistor will.
> > 
> > Best Regards,
> > 
> > Anool Mahidharia
> > Work http://www.lumetron.com/
> > DiY http://www.wyolum.com/
> > Hackaday http://hackaday.com/about/
> > HackerSpace http://www.makersasylum.com
> > Git https://github.com/anool
> > Cycling http://cyclists.in/profile/AnoolJM
> > Workouts http://www.dailymile.com/people/anool
> > Flickr http://www.flickr.com/photos/anool
> > Picasa http://picasaweb.google.com/anool.m
> > 
> > On Sun, Mar 6, 2016 at 5:12 PM, Justin Shaw notifications@github.com
> > wrote:
> > 
> > > Comment from Anool:
> > > 
> > > adding a simple transistor/FET will solve the display
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/wyolum/VeloKey/issues/5#issuecomment-192878617.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wyolum/VeloKey/issues/5#issuecomment-193254185.

## 

Justin
justin@wyolum.com

**Comment by wyojustin** [comment]
TFT_LITE now connected to A3.  Tested with 5V PWM and works great.  Anool to add fall back via for direct connection if necessary.  Will close after change.
