### ISSUE TITLE
Pin 28 on M0 is different on the bluetooth version. Disconnect

### ISSUE THREAD

**Issue by osbock** [wyolum/VeloKey#7]
Pin 16 is common gnd on both boards, connect to GND

**Comment by Anool** [comment]
Disconnected Pin 28 of M0 from GND.
Connected Pin 16 of M0 to GND.

Best Regards,

Anool Mahidharia
Work http://www.lumetron.com/
DiY http://www.wyolum.com/
Hackaday http://hackaday.com/about/
HackerSpace http://www.makersasylum.com
Git https://github.com/anool
Cycling http://cyclists.in/profile/AnoolJM
Workouts http://www.dailymile.com/people/anool
Flickr http://www.flickr.com/photos/anool
Picasa http://picasaweb.google.com/anool.m

**Comment by Anool** [comment]
Connected Pin 16 to GND
